### PR TITLE
Maintenance.vue: Remove fixed position to allow scroll on iPhone 6/7/8

### LINKED ISSUE #725: Maintenance page is too big on iPhone 6/7/8 and is not scrollable
Screenshot 2020-07-23 at 13 17 44

### PR DESCRIPTION
**Pull request by etharner**
I propose this solution to fix #725.

### CODE REVIEW

**Review by mradkov — APPROVED** [review]
This would work for now, but I think we will need to have more accurate media queries to handle such problems in the future.

File: src/views/Maintenance.vue [hunk 1]
```diff
@@ -25,12 +25,15 @@ export default {
 <style lang="scss" scoped>
 .maintenance {
   background-color: #14151f;
-  position: fixed;
   top: 0;
   bottom: 0;
   left: 0;
   right: 0;
```
Comment (davidyuk) [inline src/views/Maintenance.vue:31]: Does it have sense without `fixed`? 🤔
