### PR TITLE
Added texts, fix typos

### LINKED ISSUE #353: Update wizzard, onboarding, FAQ and tutorial texts
Some typos reported.

### PR DESCRIPTION
**Pull request by mradkov**
This closes #353

### CODE REVIEW

File: src/views/CreateProfile.vue [hunk 1]
```diff
@@ -39,12 +39,10 @@
...
               :href="chromeLink"
               target="_blank"
-            >
-              here
-            </a><br>
+            > here </a><br>
             Add the extension to your browser.<br>
-            Then the Superhero icon should appear on the
-            upper right corner of your Chrome browser tool bar.
+            Then the Superhero icon should appear on the upper right corner of your Chrome browser
```
Comment (venimus) [inline src/views/CreateProfile.vue:44]:
```suggestion
            Then the Superhero icon should appear on the upper right corner of your browser
```

File: src/views/CreateProfile.vue [hunk 2]
```diff
@@ -39,12 +39,10 @@
...
+            tool bar.
```
Comment (venimus) [inline src/views/CreateProfile.vue:45]:
```suggestion
            Then the Superhero icon should appear on the upper right corner of your browser
            toolbar.
```

File: src/views/CreateProfile.vue [hunk 3]
```diff
@@ -91,14 +87,13 @@
...
+            You’ll need this seed phrase to retrieve your wallet in case you lose access to the
+            extension for any reason (migrating to a new device, reinstalling browser, etc.)
           </p>
           <ul>
             <li>
-              <b>Write down the 12 words displayed on a piece of
-                paper to keep in a safe place only you can find.
+              <b>Write down the 12 words displayed on a piece of paper to keep in a safe place only
+                you can find.
               </b>
```
Comment (venimus) [inline src/views/CreateProfile.vue:97]:
```suggestion
              <b>Write down the 12 words displayed on a piece of paper and keep it in a safe and secret place.</b>
```

File: src/views/CreateProfile.vue [hunk 4]
```diff
@@ -113,45 +108,35 @@
...
-              Open your Superhero wallet extension.
-              The button <img src="../assets/iconExtension.svg">
-              should be in the
-              upper right of your browser tool bar.<br>
-            </li>
-            <li>
-              Click <span class="highlited">Tip</span> someone.
+              Open your Superhero wallet extension. The button
+              <img src="../assets/iconExtension.svg"> should be in the upper right of your browser
+              tool bar.<br>
```
Comment (venimus) [inline src/views/CreateProfile.vue:113]:
```suggestion
              toolbar.<br>
```

File: src/views/CreateProfile.vue [hunk 5]
```diff
@@ -113,45 +108,35 @@
...
             </li>
+            <li>Click <span class="highlited">Tip</span> someone.</li>
```
Comment (venimus) [inline src/views/CreateProfile.vue:113]:
```suggestion
            <li>Click <span class="highlited">Send Tip</span></li>
```

File: src/views/CreateProfile.vue [hunk 6]
```diff
@@ -113,45 +108,35 @@
...
-              On the next screen, fill in the required fields.
-              Enter the amount of tips you want to send, and add a
-              message telling the receiver why they’re awesome.
-            </li>
-            <li>
-              Click <span class="highlited">Send</span> tip.
+              On the next screen, fill in the required fields. Enter the amount of tips you want to
+              send, and add a message telling the receiver why they’re awesome.
             </li>
+            <li>Click <span class="highlited">Send</span> tip.</li>
```
Comment (venimus) [inline src/views/CreateProfile.vue:118]:
```suggestion
            <li>Click the <span class="highlited">Send Tip</span> button below.</li>
```

File: src/views/CreateProfile.vue [hunk 7]
```diff
@@ -193,30 +178,28 @@
...
             >
-              here
-            </a>.
+              here </a>.
           </p>
           <p>
-            You can claim as many names on Superhero as you want.
-            But as a rule, you must have a minimum of XX AE in your wallet.
+            You can claim as many names on Superhero as you want. But as a rule, you must have a
+            minimum of XX AE in your wallet.
```
Comment (venimus) [inline src/views/CreateProfile.vue:200]: XX ? should be specified

File: src/views/FAQ.vue [hunk 8]
```diff
@@ -11,13 +11,13 @@
           if you can't find the answer of you question below visit our
           <router-link to="/create-profile">
             Tutorial Page
-          </router-link>to
-          <br>receive more information about using Superhero platform and wallet.
+          </router-link>to <br>receive more
+          information about using Superhero platform and wallet.
```
Comment (venimus) [inline src/views/FAQ.vue:15]:
```suggestion
          </router-link> to<br>
          receive more information about using Superhero platform and wallet.
```

File: src/views/FAQ.vue [hunk 9]
```diff
@@ -32,33 +32,29 @@
...
-          <br>No 3
-          <sup>rd</sup> party custodians will control
-          content, or your ability to tip or receive tips.
-          <br>Superhero is you and you and you and you… Without any “them” in-between.
+          >aeternity blockchain</a>. <br>Anyone,
+          anywhere may use the platform. <br>Other websites may use the platform. <br>All have
+          uncensored, equal ability to be Superhero. <br>As P2P – the only ones who are not part
+          of Superhero intermediaries. <br>No 3 <sup>rd</sup> party custodians will control
+          content, or your ability to tip or receive tips. <br>Superhero is you and you and you
+          and you… Without any “them” in-between.
```
Comment (venimus) [inline src/views/FAQ.vue:40]: the linter requires `<br>` to be the last on the line with a break after it (AFAIK)
```suggestion
          >aeternity blockchain</a>.<br>
          Anyone, anywhere may use the platform.<br>
          Other websites may use the platform.<br>
          All have uncensored, equal ability to be Superhero.<br>
          As P2P – the only ones who are not part of Superhero intermediaries.<br>
          No 3 <sup>rd</sup> party custodians will control content,
          or your ability to tip or receive tips.<br>
          Superhero is you and you and you and you… Without any “them” in-between.
```

File: src/views/FAQ.vue [hunk 10]
```diff
@@ -32,33 +32,29 @@
...
         </expandable-block>
         <expandable-block :title="'How does Superhero work?'">
           Superhero is built on aeternity blockchain.
-          <br>Because it is built on blockchain, actions are transparent.
-          <br>Because it is built on the blockchain, actions are published forever.
-          <br>Blockchain has promised a more free and decentralized future for society.
-          <br>Superhero used blockchain as its foundation to make that promise a reality.
-          <br>Superhero is an online community making a tangible difference in the real world.
+          <br>Because it is built on blockchain, actions are transparent. <br>Because it is
```
Comment (venimus) [inline src/views/FAQ.vue:44]: the linter requires `<br>` to be the last on the line with a break after it (AFAIK)

Comment (venimus) [reply src/views/FAQ.vue:44]: Tough not a problem for me per se

Comment (mradkov) [reply src/views/FAQ.vue:44]: > the linter requires `<br>` to be the last on the line with a break after it (AFAIK)

Strange, because I run it before every commit and it does not complain.

File: src/views/CreateProfile.vue (hunk 7 above)
Comment (mradkov) [reply src/views/CreateProfile.vue:200]: Good question. I guess we should not limit this to specific amount as it will eventually depend on the length of the name that the user want to claim.

File: src/views/FAQ.vue (hunk 10 above)
Comment (venimus) [reply src/views/FAQ.vue:46]: I think it is a warning which fails on travis, but might not fail locally

Comment (venimus) [reply src/views/FAQ.vue:46]: But if it passes then just don't change it. May be i'm mistaken

File: src/views/CreateProfile.vue (hunk 7 above)
Comment (venimus) [reply src/views/CreateProfile.vue:200]: I though about that, currently from what I understood you need to have at least 12 chars to claim from within the wallet which requires 2-3AE for it (or something like that) I think that might be the minimum we can put here. You will require more for shorter but you functionally need to use the auctions, which is not covered here. May be we can just mention that, so ppl are not confused

Comment (mradkov) [reply src/views/CreateProfile.vue:200]: I thought of just slightly modifying the text to not point to an exact value.

"... you must have enough AE to cover the price for the name ... "
